### ISSUE TITLE
High CPU load playing SIDs

### ISSUE THREAD

**Issue by knochenhans** [HippoPlayer/HippoPlayer#163]
I’m experiencing a exceptionally high CPU (i5-4300M) load when playing SIDs, leading to dropouts in the output stream.

**Comment by emoon** [comment]
Interesting. I think I have quality set to highest by default, but I would figure it should would on an i5. I'm currently in work of adding support for settings for the playback plugins so I will expose the quality setting then. Still I think it should work on such a fast CPU anyway. I can try to add some basic profiling support and see if it helps to narrow it down

**Comment by emoon** [comment]
One question: Does SID playback work worse after version `0.1.8` ? I switched audio backend in `0.1.8` and it may affect the CPU usage a bit.

**Comment by emoon** [comment]
I investigated this a bit and I don't see any big CPU usage for the machine I'm testing on (laptop i7-8750H) the VS profiler say ~1% CPU usage across all cores

![image](https://user-images.githubusercontent.com/350822/91692033-ff441700-eb68-11ea-9236-a5be38243882.png)

I do notice some "crackling" sound tho in some SIDs which is bad but in my case not related to CPU usage so I will have to investigate that.

**Comment by emoon** [comment]
I fixed the Bad sound/crackling issue. I'm unsure if it's the same as you are seeing, but try `0.1.12` when the CI has produced the build.

**Comment by emoon** [comment]
Give https://github.com/emoon/HippoPlayer/releases/tag/0.1.12 a go and see if it fixes the issue

**Comment by knochenhans** [comment]
Unfortunately, the problem remains for me in the current version. I have to give older versions a try (having some problems compiling them), got the vague feeling it didn’t show there. Oh and I forgot to add I’m using Linux (PulseAudio), maybe this plays a role.

**Comment by emoon** [comment]
Oh, I see. I use PulseAudio under Linux as well but my desktop machine is quite fast. Also make sure you build the release version if you are compiling the code yourself.

**Comment by knochenhans** [comment]
Ok, I tried 0.1.6.3, the problem is there as well. I can’t imagine this being a performance problem with my CPU though, never saw anything like this with other software playing SIDs ;) (like foobar2000 or DeliPlayer 2)

**Comment by emoon** [comment]
Did you try to build in release mode?

**Comment by knochenhans** [comment]
Ha, good call! This brought down the CPU core load to ~5–10%

**Comment by emoon** [comment]
cool. Does it play correct now?

**Comment by knochenhans** [comment]
Yes, plays fine now. I’m sure the dropouts just resulted from the CPU overload.

**Comment by emoon** [comment]
Cool. The latest version should play correct also (prev version had some other (non-CPU related)) issues.
